version: '3.6'

services:

  nginx:
    container_name: salary_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/data/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker/containers/nginx/conf:/etc/nginx/conf.d/:ro
      - .:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    container_name: salary_php
    build:
      context: ./docker/containers/php
    volumes:
      - .:/var/www/html
    restart: always
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    links:
      - php-db
      - "redis:redis_local"
    depends_on:
      - php-db

  php-db:
    container_name: salary_db
    image: mysql:8.0
    command: [ --default-authentication-plugin=mysql_native_password ]
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - '3807:3306'
    restart: always
    environment:
      MYSQL_DATABASE: 'salary'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '00000000'
      MYSQL_ROOT_PASSWORD: '00000000'

  redis:
    container_name: salary_redis
    image: bitnami/redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "6379:6379"

